# MAIN Monitor
preload = /mnt/ETC/Things/Pictures & Videos/apps.49995.67561953351040807.9514dbc1-3b51-4880-b41e-e7ce5457b822.f9b6a740-b97b-4ad1-bf2b-5cc03d050f4b.jpg
wallpaper = DP-1, /mnt/ETC/Things/Pictures & Videos/apps.49995.67561953351040807.9514dbc1-3b51-4880-b41e-e7ce5457b822.f9b6a740-b97b-4ad1-bf2b-5cc03d050f4b.jpg
# .. more preloads


# CRT Monitor
preload = /mnt/ETC/Things/Pictures & Videos/ECbNkMgVUAQSAxS.jpg
wallpaper = DP-2, /mnt/ETC/Things/Pictures & Videos/ECbNkMgVUAQSAxS.jpg
# .. more preloads

# Third Monitor
preload = /mnt/ETC/Things/Pictures & Videos/Windows backup Picuters & Videos/pictuers/FdslUR9WAAE27Ka.jpg
wallpaper = DP-3, /mnt/ETC/Things/Pictures & Videos/Windows backup Picuters & Videos/pictuers/FdslUR9WAAE27Ka.jpg
# .. more monitors

#enable splash text rendering over the wallpaper
splash = false




#fully disable ipc
# ipc = off
