
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox


#exec-once = swaync

exec-once = hypridle & hyprpaper & nm-applet
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl dispatch workspace 1
exec-once = copyq --start-server
exec-once = hyprpm reload -n
exec-once = ~/.azotebg-hyprland
#exec-once = waybar
exec-once = waypaper --restore
exec-once = noctalia-shell --no-duplicate




#exec-once = nwg-dock-hyprland -r -i 35 -w 10 -mb 2 -ml 10 -mr 10 -x      #-c "rofi -show drun" -lp start
#exec-once = ~/scripts/waybar-rld.sh
#exec-once = ags run --gtk4 -d ~/git-source/epik-shell/
# Dark theme
#exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"   # for GTK3 apps
#exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
